---
- name: Gestionar servicios con systemctl
  hosts: all
  become: yes
  tasks:
    - name: Detener el servicio
      systemd:
        name: apache2
        state: stopped

    - name: Habilitar el servicio para que se inicie al arrancar
      systemd:
        name: apache2
        enabled: yes

    - name: Iniciar el servicio
      systemd:
        name: apache2
        state: started

    - name: Reiniciar el servicio
      systemd:
        name: apache2
        state: restarted
